services:
  web:
    container_name: 'openchemie-service'
    build: .
    ports:
     - "8000:80"
    volumes:
     - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  retrosynthesis-api:
    container_name: 'retrosynthesis-api'
    build:
      context: ./retrosynthesis
      dockerfile: Dockerfile
    env_file:
      - ./retrosynthesis/.env-non-dev
    ports:
      - "8000:8000"
    restart: unless-stopped
